[project]
name = "custom-unix-terminal"
version = "3"
description = "A project that uses Zensical to host documentation for customizations of my Unix terminal."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "zensical>=0.0.15",
]
